name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        # pip install -r requirements.txt
        pip install pylint
    - name: Rename info-template.py to info.py
      working-directory: .
      run: |
        ls -a
        touch test
        ls -a
        # mv info-template.py info.py
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
